version: '3'

services:

    app:
        build: .
        container_name: app
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravel_microservico
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes:
            - .:/var/www/
        networks:
            - app-newtwork
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: dockerize -template ./.docker/app/nginx.conf:./.docker/nginx/nginx.conf  ./.docker/entrypoint-nginx.sh
        environment:
            - HOST=app
            - PORT=9000
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-newtwork
        depends_on:
            - app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel_microservico
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-newtwork

    redis:
        image: redis
        expose:
          - 6379
        networks:
          - app-newtwork

networks:
    app-newtwork:
        driver: bridge